# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre de cup\xf3n')),
                ('puntos', models.IntegerField(blank=True, verbose_name='Puntos')),
                ('Descripcion', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('is_active', models.BooleanField(default=True, verbose_name='\xbfEst\xe1 activo?')),
            ],
            options={
                'verbose_name': 'Cup\xf3n',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='\xbfEst\xe1 activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='T\xedtulo')),
                ('autor', models.CharField(blank=True, max_length=500, verbose_name='Autor')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('is_active', models.BooleanField(default=True, verbose_name='\xbfEst\xe1 activo?')),
                ('foto', models.CharField(max_length=255, verbose_name='Foto')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Libro', to='snippets.Genero', verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregu', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('rc', models.CharField(blank=True, max_length=500)),
                ('r', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='\xbfEst\xe1 activo?')),
                ('r2', models.CharField(max_length=255)),
                ('r3', models.CharField(max_length=255)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Libro', to='snippets.Libro', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=255, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='\xbfEst\xe1 activo?')),
                ('puntos', models.IntegerField(blank=True, verbose_name='Puntos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
