# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'G\xe9nero', 'verbose_name_plural': 'G\xe9neros'},
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Libro', to='snippets.Genero', verbose_name='G\xe9nero'),
        ),
    ]
